backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "assets/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", dateFormat: "DD.MM.YYYY" }
      # - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          hint: "Only allows 255 characters",
        }
      - { label: "Body", name: "body", widget: "markdown" }
